name: mesongs
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - plyfile=0.8.1
  - python=3.10
  - pytorch==2.4.0
  - torchaudio==2.4.0
  - torchvision==0.19.0
  - pytorch-cuda=12.1
  - tqdm
